import { access, chmod, mkdir, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import type { Address, Hex } from 'viem';
import { generatePrivateKey, privateKeyToAccount } from 'viem/accounts';
import { normalizeAddress, ValidationError } from './validation.js';

export const DEFAULT_WALLET_PRIVATE_KEY_ENV = 'UVP_ETH_DEPLOYER_PRIVATE_KEY';
export const DEFAULT_WALLET_ADDRESS_ENV = 'UVP_ETH_DEPLOYER_ADDRESS';

export interface WalletEnvOptions {
  readonly privateKeyEnv?: string;
  readonly addressEnv?: string;
}

export interface GeneratedWalletEnv {
  readonly address: Address;
  readonly privateKey: Hex;
  readonly privateKeyEnv: string;
  readonly addressEnv: string;
  readonly envText: string;
}

export interface WriteWalletEnvFileOptions extends WalletEnvOptions {
  readonly overwrite?: boolean;
}

export interface WalletEnvFileResult {
  readonly address: Address;
  readonly envFile: string;
  readonly privateKeyEnv: string;
  readonly addressEnv: string;
  readonly overwritten: boolean;
}

export interface FaucetInfo {
  readonly network: 'base-sepolia';
  readonly chainId: 84532;
  readonly nativeSymbol: 'ETH';
  readonly address?: Address;
  readonly links: readonly string[];
  readonly notes: readonly string[];
}

const PRIVATE_KEY_RE = /^0x[a-fA-F0-9]{64}$/;

export function createWalletEnv(options: WalletEnvOptions = {}): GeneratedWalletEnv {
  const privateKeyEnv = options.privateKeyEnv ?? DEFAULT_WALLET_PRIVATE_KEY_ENV;
  const addressEnv = options.addressEnv ?? DEFAULT_WALLET_ADDRESS_ENV;
  const privateKey = generatePrivateKey();
  const address = privateKeyToAccount(privateKey).address;
  return {
    address,
    privateKey,
    privateKeyEnv,
    addressEnv,
    envText: formatWalletEnv({ privateKey, address, privateKeyEnv, addressEnv }),
  };
}

export async function writeWalletEnvFile(
  filePath: string,
  options: WriteWalletEnvFileOptions = {},
): Promise<WalletEnvFileResult> {
  if (!filePath || filePath.trim().length === 0) {
    throw new ValidationError('env file path is required');
  }

  const envFile = resolve(filePath);
  const overwritten = await fileExists(envFile);
  if (overwritten && !options.overwrite) {
    throw new ValidationError(`${envFile} already exists; pass --overwrite to replace it`);
  }

  const wallet = createWalletEnv(options);
  await mkdir(dirname(envFile), { recursive: true });
  await writeFile(envFile, wallet.envText, { mode: 0o600 });
  // writeFile's `mode` only applies to files it creates: with --overwrite the
  // file already exists and keeps its (possibly looser) permissions, so the
  // owner-only mode must be re-asserted explicitly.
  await chmod(envFile, 0o600);
  return {
    address: wallet.address,
    envFile,
    privateKeyEnv: wallet.privateKeyEnv,
    addressEnv: wallet.addressEnv,
    overwritten,
  };
}

export function addressFromPrivateKey(privateKey: string, fieldName = 'privateKey'): Address {
  const normalized = normalizePrivateKey(privateKey, fieldName);
  return privateKeyToAccount(normalized).address;
}

export function getFaucetInfo(network = 'base-sepolia', address?: string): FaucetInfo {
  if (network !== 'base-sepolia') {
    throw new ValidationError(`unsupported faucet network: ${network}`);
  }

  const normalizedAddress = address ? normalizeAddress(address, 'address') : undefined;
  return {
    network: 'base-sepolia',
    chainId: 84532,
    nativeSymbol: 'ETH',
    ...(normalizedAddress ? { address: normalizedAddress } : {}),
    links: [
      'https://docs.base.org/chain/network-faucets',
      'https://docs.cdp.coinbase.com/faucets/docs/welcome',
    ],
    notes: [
      'Request Base Sepolia ETH for deployer gas.',
      'Funding adapter tokens are outside the current state-machine smoke path.',
    ],
  };
}

function normalizePrivateKey(privateKey: string, fieldName: string): Hex {
  if (!PRIVATE_KEY_RE.test(privateKey)) {
    throw new ValidationError(`${fieldName} must be a 32-byte 0x-prefixed private key`);
  }
  return privateKey as Hex;
}

function formatWalletEnv(input: {
  readonly privateKey: Hex;
  readonly address: Address;
  readonly privateKeyEnv: string;
  readonly addressEnv: string;
}): string {
  return [
    '# Generated by uvp-executor wallet new. Do not commit this file.',
    `${input.privateKeyEnv}=${input.privateKey}`,
    `${input.addressEnv}=${input.address}`,
    '',
  ].join('\n');
}

async function fileExists(filePath: string): Promise<boolean> {
  try {
    await access(filePath);
    return true;
  } catch {
    return false;
  }
}
